spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.20:5432/simple_cron
    username: postgres
    password: root1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: true

  data:
    mongodb:
      database: simple_cron
      host: 192.168.31.20
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html #模板后缀
    encoding: UTF-8 #编码
    check-template-location: true


  application:
    name: simplecron

  profiles:
    active: dev