spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.20:5432/simple_cron
    username: postgres
    password: root1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: true

  data:
    mongodb:
      database: simple_cron
      host: 192.168.31.20
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin
  thymeleaf:
    cache: true
    enabled: true
    mode: HTML

  application:
    name: simplecron

  profiles:
    active: dev