spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin
      exclude: WEB-INF/**

  redis:
    database: 0

server:
  port: 8080
  host: 127.0.0.1