spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.20:5432/simple_cron
    username: postgres
    password: root1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: true

  data:
    mongodb:
      database: simple_cron
      host: 192.168.31.20
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html #模板后缀
    encoding: UTF-8 #编码
    check-template-location: true

  application:
    name: simplecron

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #  mail:
  #    host: smtp.office365.com
  #    username: fklvch@outlook.com
  #    password: =b,x@]pfw_7G-2<O
  #    default-encoding: UTF-8
  #    port: 587
  #    properties:
  #      mail:
  #        smtp:
  #          port: 587
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true
  #    protocol: smtps

  jackson:
    time-zone: GMT+8
    deserialization:
      # 遇到未知属性就解析失败
      failOnUnknownProperties: false
      # 遇到空字符串对象解析为 null
      acceptEmptyStringAsNullObject: true
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false


minio:
  bucketName: simple-cron
  accessKey: myminioadmin
  secretKey: myminioadmin
  endpoint: http://192.168.31.20:9000/